name: first_flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_svg: ^0.17.4
  carousel_pro: ^1.0.0
  bottom_navy_bar: ^5.6.0
  translator: ^0.1.6+1
  carousel_slider: ^3.0.0
  curved_navigation_bar: ^0.3.7
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
     - images/
