name: first_flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_html: ^1.3.0
  shared_preferences:
  flutter_spinkit: ^4.1.2
  image_picker: ^0.7.4
  dropdownfield: ^1.0.3
  carousel_pro: ^1.0.0
  bottom_navy_bar: ^5.6.0
  carousel_slider: ^3.0.0
  curved_navigation_bar: ^0.3.7
  dio: ^4.0.0
  provider: ^5.0.0
  flutter_facebook_auth: ^3.3.2
  paypal: ^0.0.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
     - images/
     - assets/img/
